### ISSUE TITLE
Sign your code?

### ISSUE THREAD

**Issue by DiagonalArg** [ryran/pyrite#18]
You should sign your code, man.  Or at least give us some hashes.

(Thanks for your work!)

**Comment by ryran** [comment]
I can't believe a whole year went by ... more. Closing as dupe of #7. I really do plan to look into this next month. Will comment there if I need help.

**Comment by ryran** [comment]
Finally done.

https://github.com/ryran/pyrite/releases/tag/v1.0.2

I'll be using signed tags from now on, as well as signing all commits.

**Comment by DiagonalArg** [comment]
Dude!  Thank you.  Great little project, by the way ...
