### ISSUE TITLE
pyrite doesn't work in rhel6 or centos6

### ISSUE THREAD

**Issue by mariarti** [ryran/pyrite#4]
# pyrite
Traceback (most recent call last):
  File "/usr/bin/pyrite", line 37, in <module>
    import modules.core
  File "/usr/share/pyrite/modules/core.py", line 415
    if startup or self.g_cipher.get_active() in {0, 2}:
                                                  ^
SyntaxError: invalid syntax

Help pls!

**Comment by ryran** [comment]
I'm never going to get to this. If someone else wants to create a rhel-6-compatible-branch, feel free to re-open.
